//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class medbase201507Entities : DbContext
    {
        public medbase201507Entities()
            : base("name=medbase201507Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hbasememb> hbasememb { get; set; }
        public virtual DbSet<hcheckmemb> hcheckmemb { get; set; }
        public virtual DbSet<hdatadepdiag> hdatadepdiag { get; set; }
        public virtual DbSet<hdatadeptest> hdatadeptest { get; set; }
        public virtual DbSet<hdatadiag> hdatadiag { get; set; }
    }
}
